apiVersion: apps/v1beta1
kind: Deployment
metadata:
name: azure-DevOps
spec:
replicas: 1
template:
metadata:
labels:
app: azure-DevOps
spec:
containers:
– name: azure-DevOps
image: redis
ports:
– containerPort: 6379
name: redis
—
apiVersion: v1
kind: Service
metadata:
name: azure-DevOps
spec:
ports:
– port: 6379
selector:
app: azure-DevOps
—
apiVersion: apps/v1beta1
kind: Deployment
metadata:
name: azure-DevOps
spec:
replicas: 1
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
minReadySeconds: 5
template:
metadata:
labels:
app: azure-DevOps
spec:
containers:
– name: AzureDevOps
image: dockerwebapptest12.azurecr.io/sahilhulagepythonsamplevscodeflasktutorial:189
ports:
– containerPort: 80
resources:
requests:
cpu: 250m
limits:
cpu: 500m
env:
– name: REDIS
value: “azure-vote-back”
—
apiVersion: v1
kind: Service
metadata:
name: azure-vote-front
spec:
type: LoadBalancer
ports:
– port: 80
selector:
app: azure-vote-front
